
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package Compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISTINTO = 14;
  public static final int ASIGNAR = 17;
  public static final int ENTERO = 34;
  public static final int RESTA = 6;
  public static final int LPAREN = 2;
  public static final int MENORI = 12;
  public static final int INT = 20;
  public static final int RPAREN = 3;
  public static final int AND = 16;
  public static final int PINWRITER = 28;
  public static final int IGUAL = 13;
  public static final int LLLAVE = 18;
  public static final int OR = 15;
  public static final int CLASS = 22;
  public static final int RLLAVE = 19;
  public static final int SUMA = 5;
  public static final int MAIN = 21;
  public static final int IF = 23;
  public static final int ID = 33;
  public static final int PTOCOMA = 4;
  public static final int EOF = 0;
  public static final int PRODUCTO = 7;
  public static final int PRINTS = 26;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int PRINTN = 27;
  public static final int MENOR = 9;
  public static final int BREAK = 31;
  public static final int MAYOR = 10;
  public static final int PAINTER = 30;
  public static final int TIMER = 29;
  public static final int ELSE = 24;
  public static final int CADENATEXTO = 35;
  public static final int WHILE = 25;
  public static final int MAYORI = 11;
  public static final int DIVISION = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "PTOCOMA",
  "SUMA",
  "RESTA",
  "PRODUCTO",
  "DIVISION",
  "MENOR",
  "MAYOR",
  "MAYORI",
  "MENORI",
  "IGUAL",
  "DISTINTO",
  "OR",
  "AND",
  "ASIGNAR",
  "LLLAVE",
  "RLLAVE",
  "INT",
  "MAIN",
  "CLASS",
  "IF",
  "ELSE",
  "WHILE",
  "PRINTS",
  "PRINTN",
  "PINWRITER",
  "TIMER",
  "PAINTER",
  "BREAK",
  "COMA",
  "ID",
  "ENTERO",
  "CADENATEXTO"
  };
}

