/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principales;


import clases.MyPaint;
import java.awt.Color;
import java.awt.Font;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.Method;
import javax.swing.Painter;
import javax.swing.Timer;
import javax.swing.UIDefaults;
import javax.swing.UIManager;

/**
 *
 * @author Kleinz
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    private ActionListener al;
    private Timer t;
    private IDE newIDE = new IDE();
    
    private Color myBackgroundbar = new Color(0,102,255,255);//255,51,102
    private Color myForegroundbar = new Color(0,0,0);
    private Color componentColor = new Color(102,102,102,150);
    
    public Splash() {
        
        
        al = new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                if(progress.getValue()<100){
                    progress.setValue(progress.getValue()+1);
                }
                else{
                  t.stop();
                  invokeIDE();
                }
            }
        };
        t = new Timer(/*((int) newIDE.timeExecution())*/50,al);
        
        initComponents();
        copy_symbol.setFont(new Font("Tahoma", Font.BOLD, 10));
        reserved_rights.setFont(new Font("Tahoma", Font.BOLD, 10));
        copy_symbol.setText("\u00a9 Copyright 2015");
        copy_symbol.setForeground(new Color(153,0,0));
        reserved_rights.setForeground(new Color(51,51,51));
        setColorProgressBar();
        setLocationRelativeTo(null);
        progress.setStringPainted(true);
        progress.setForeground(myForegroundbar);
       
        progress.setString("Initializing Components");
        progress.setFont(new Font("Tahoma", Font.BOLD, 12));
        setOpaque(this, false);
        
       
        t.start();
       
    }
    private void setColorProgressBar(){
        UIDefaults defaults = new UIDefaults();
        Painter painter = new MyPaint(myBackgroundbar);
        Painter painter2 = new MyPaint(componentColor);
        defaults.put("ProgressBar[Enabled].foregroundPainter", painter);
        defaults.put("ProgressBar[Enabled+Finished].foregroundPainter", painter);
        defaults.put("ProgressBar[Enabled].backgroundPainter", painter2);
        progress.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
        progress.putClientProperty("Nimbus.Overrides", defaults);
    
    }
    public static void setOpaque(Window window, boolean opaque) {

    try {

        Class<?> awtUtilsClass = Class.forName("com.sun.awt.AWTUtilities");
        if (awtUtilsClass != null) {

            Method method = awtUtilsClass.getMethod("setWindowOpaque", Window.class, boolean.class);
            method.invoke(null, window, opaque);

        }

    } catch (Exception exp) {
    }

}
    public void invokeIDE(){
        
       
        
        newIDE.setLocationRelativeTo(null);
        newIDE.setVisible(true);
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UIManager.put("ProgressBar.selectionBackground", Color.black);
        UIManager.put("ProgressBar.selectionForeground", Color.white);
        UIManager.put("ProgressBar.foreground", Color.red);
        progress = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        copy_symbol = new javax.swing.JLabel();
        reserved_rights = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        progress.setBackground(new java.awt.Color(153,0,102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rasby3.png"))); // NOI18N

        copy_symbol.setText("jLabel2");

        reserved_rights.setText(". All reserved rights by RasbyCorp.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(copy_symbol)
                                .addGap(0, 0, 0)
                                .addComponent(reserved_rights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copy_symbol)
                    .addComponent(reserved_rights))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copy_symbol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar progress;
    private javax.swing.JLabel reserved_rights;
    // End of variables declaration//GEN-END:variables
}

